// Generated by CoffeeScript 1.4.0
(function() {
  var ready;

  ready = function() {
    $('#nav_flag').mouseenter(function() {
      return $('#nav_flag').animate({
        top: '0'
      });
    });
    return $('#nav_flag').mouseleave(function() {
      return $('#nav_flag').animate({
        top: '-32px'
      }, "fast");
    });
  };

  $(document).ready(ready);

}).call(this);
